### ISSUE TITLE
Does it work on Windows?

### ISSUE THREAD

**Issue by seagle0128** [lujun9972/org-preview-html#15]
I am using `org-mode` with GNU Emacs on Windows and Linux. It works well on Linux, but doesn't work on  Windows. Am I missing something here?

**Comment by lujun9972** [comment]
I haven't tried it on Windows yet.
Is there any error message?

**Comment by seagle0128** [comment]
I got this message: `org-export-to-file: Output file not writable`.

**Comment by seagle0128** [comment]
Thanks for the quick fixing!
