### ISSUE TITLE
Org itself contains a library named org-eww

### ISSUE THREAD

**Issue by tarsius** [lujun9972/org-preview-html#5]
You should probably rename your library.

http://repo.or.cz/org-mode.git/blob/ddd58ff99a8684f6bcae24ffa5050857f533e26d:/contrib/lisp/org-eww.el (from the `maint` branch).

**Comment by heikkil** [comment]
I'd like to propose a name change to the package: org-preview-html

Descriptive and generic name
Would get rid of the name conflict with already existing org-eww.el in org-plus-contrib.
There should be no need to include eww into the name. There could be more than one backend.
This would pave a way to other similarly named packages with different output formats.
