### ISSUE TITLE
Windowless mode?

### ISSUE THREAD

**Issue by alphapapa** [lujun9972/org-preview-html#8]
Hi, this looks like a neat package.  One suggestion, it would be nice to have a command instead of just a mode.  That way, when you want to preview the changes, you could run a single command and see it (instead of having to go through the org export dispatcher), but you wouldn't have to have the preview window open all the time, taking up screen space.  :)

**Comment by lujun9972** [comment]
I have made 'org-preview-html/preview` to be a command so you can execute it without turn on the org-preview-html-mode.
Is that what you want?

**Comment by alphapapa** [comment]
That's cool, thanks.  :)
